### ISSUE TITLE
Not getting SMS when I register new user

### ISSUE THREAD

**Issue by kamipatel** [awslabs/aws-mobile-react-sample#16]
Is that a bug? Needs a config?

**Comment by mlabieniec** [comment]
@kamipatel do you have a aws-exports.js file in your src directory and initialize a new project with the cli (or console)? The configuration is read from the exports file:
https://github.com/awslabs/aws-mobile-react-sample/blob/master/client/src/index.js#L22

Also, for this feature you need to make sure you have  user signin enabled as well, if you imported the zip file with the "Deploy to Mobile Hub" button in the readme this would have created all this for you. Otherwise, you would need to make sure you have user-signin enabled

     awsmobile features
     > user-signin

**Comment by kamipatel** [comment]
Yes I do have aws-exports.js file in your src directory 
Yes I have awsmobile features
 > user-signin
enabled.
Just not able to receive any SMS. Also not able disable MFA to bypass the issue. :-(
Please help. I have already tried 3 times redeploying.

**Comment by AustinDeric** [comment]
I am also not able to receive sms messages.  I have aws-exports.js in my src directory and i confirmed that user-signin is enabled in awsmobile features.
